target: _site

data:
  - _data

pageviews:
  - _pages

collections:
  - name: user_documentation
    folder: _documentation/user
  - name: bzfs_api_events
    folder: _documentation/developer/bzfs_api_events
  - name: bzfs_api_objects
    folder: _documentation/developer/bzfs_api_objects

exclude:
  - COPYING
  - README.md

debug: false

github:
  dev_repo: BZFlag-Dev/bzflag
  dev_branch: 2.4
