target: _site

data:
  - _data

pageviews:
  - _pages

collections:
  - name: documentation
    folder: _documentation

exclude:
  - COPYING
  - README.md

debug: false

# Include the .html extension in links so that you can test with a basic webserver configuration.
localDevelopment: false
