target: _site

data:
  - _data

pageviews:
  - _pages

collections:
  - name: documentation
    folder: _documentation
  - name: api_events
    folder: _apiEvents

exclude:
  - COPYING
  - README.md

debug: false
