target: _site

data:
  - _data

datasets:
  - name: downloads_bzflag
    folder: _datasets/downloads/bzflag
  - name: downloads_bzeditw32
    folder: _datasets/downloads/bzeditw32

pageviews:
  - _pages

collections:
  - name: user_documentation
    folder: _documentation/user
  - name: bzfs_api_events
    folder: _documentation/developer/bzfs_api_events

exclude:
  - COPYING
  - README.md

debug: false

github:
  dev_repo: BZFlag-Dev/bzflag
  dev_branch: 2.4
